/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package startrekking;
import gamestate.*;
import javax.swing.JPanel;
import util.KeyHandler;
/**
 *
 * @author Star Trekking
 */
public class Window extends javax.swing.JFrame {
    private final GameStateManager gameStateManager; //gestisce il panel
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        gameStateManager = new GameStateManager(this);
        this.setContentPane(gameStateManager.getState().getPanel());
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * Set the contentPane based on the game state.
     * @param panel panel affected by game state.
     */
    public void setPanel(JPanel panel){
        this.setContentPane(gameStateManager.getState().getPanel());
        this.getContentPane().setSize(this.getSize());
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
