/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import gamestate.GameOverState;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author StarTrekking
 *
 * Class to define the panel when the the game pass in the game over state
 */
public class GameOverPanel extends javax.swing.JPanel{

    private final GameOverState state;
    private BufferedImage screen;
    BufferedImage gameOverIcon_black;

    BufferedImage menuIcon_black;
    BufferedImage restartIcon_black;

    BufferedImage menuIcon_yellow;
    BufferedImage restartIcon_yellow;

    /**
     * Creates new form GameOverPanel
     *
     * @param state is the state in which the game must go
     * @throws java.io.IOException if the application can't read some files
     */
    public GameOverPanel(GameOverState state) throws IOException {
        this.state = state;

        screen = ImageIO.read(getClass().getResource("/screen/forest.png"));

        initComponents();
        gameOverIcon_black = ImageIO.read(getClass().getResource("/menuIcon/gameover.png"));
        menuIcon_black = ImageIO.read(getClass().getResource("/menuIcon/back_black.png"));
        restartIcon_black = ImageIO.read(getClass().getResource("/menuIcon/restart_black.png"));

        restartIcon_yellow = ImageIO.read(getClass().getResource("/menuIcon/restart_yellow.png"));
        menuIcon_yellow = ImageIO.read(getClass().getResource("/menuIcon/back_yellow.png"));

        titleLabel1.setIcon(new javax.swing.ImageIcon(gameOverIcon_black));

        initIcon();

        this.setVisible(true);
        this.setSize(GameFrame.WIDTH, GameFrame.HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel1 = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();

        titleLabel1.setFont(new java.awt.Font("Beirut", 2, 36)); // NOI18N
        titleLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titleLabel1buttonPressedHandler(evt);
            }
        });

        restartButton.setBorder(null);
        restartButton.setBorderPainted(false);
        restartButton.setContentAreaFilled(false);
        restartButton.setFocusPainted(false);
        restartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restartButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restartButtonMouseExited(evt);
            }
        });
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setBorder(null);
        mainMenuButton.setBorderPainted(false);
        mainMenuButton.setContentAreaFilled(false);
        mainMenuButton.setFocusable(false);
        mainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainMenuButtonMouseExited(evt);
            }
        });
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(restartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initIcon() {

        restartButton.setIcon(new javax.swing.ImageIcon(restartIcon_black));
        restartButton.setBorder(null);

        mainMenuButton.setIcon(new javax.swing.ImageIcon(menuIcon_black));
        mainMenuButton.setBorder(null);

    }
    private void titleLabel1buttonPressedHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabel1buttonPressedHandler

    }//GEN-LAST:event_titleLabel1buttonPressedHandler

    private void restartButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartButtonMouseEntered

        restartButton.setIcon(new javax.swing.ImageIcon(restartIcon_yellow));
        restartButton.setBorder(null);
    }//GEN-LAST:event_restartButtonMouseEntered

    private void restartButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartButtonMouseExited

        restartButton.setIcon(new javax.swing.ImageIcon(restartIcon_black));
        restartButton.setBorder(null);
    }//GEN-LAST:event_restartButtonMouseExited

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        restartButton.setIcon(new javax.swing.ImageIcon(restartIcon_black));
        state.handleNext(0);
    }//GEN-LAST:event_restartButtonActionPerformed

    private void mainMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuButtonMouseEntered

        mainMenuButton.setIcon(new javax.swing.ImageIcon(menuIcon_yellow));
        mainMenuButton.setBorder(null);
    }//GEN-LAST:event_mainMenuButtonMouseEntered

    private void mainMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuButtonMouseExited

        mainMenuButton.setIcon(new javax.swing.ImageIcon(menuIcon_black));
        mainMenuButton.setBorder(null);
    }//GEN-LAST:event_mainMenuButtonMouseExited

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        mainMenuButton.setIcon(new javax.swing.ImageIcon(menuIcon_black));
        state.handleNext(1);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(screen, 0, 0, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton restartButton;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables

}
